<?php

namespace Meldon\WotRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActionDieDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionDieDetailsRepository extends EntityRepository
{
    public function getDetailsArrayByNumber(Side $side)
    {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT d FROM WotRBundle:ActionDieDetails d '
                        . 'INDEX BY d.number '
                        . 'WHERE d.side = :side ' )
                ->setParameter('side',$side)
                ->getResult();
    }
}
