<?php

namespace Meldon\WotRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionDetailsRepository extends EntityRepository
{
    public function getActionsForDice($adD, $qb = true)
    {
        return $this
                ->createQueryBuilder('a')
                ->leftJoin('a.actionDieDetails','ad')
                ->where('ad.id = :adID')
                ->setParameter('adID',$adD->getDetailsID())
                ->getQuery()
                ->getResult();
    }
}
