<?php

namespace Meldon\WotRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardGroupRepository extends EntityRepository
{

}