<?php

namespace Meldon\WotRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardEntryDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardEntryDetailsRepository extends EntityRepository
{
    public function getStartCards(Scenario $scenario)
    {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT ced, cd FROM WotRBundle:CardEntryDetails ced '
                        . 'JOIN ced.cardDetails cd '
                        . 'WHERE ced.scenario = :id '
                        . 'AND ced.turn = 1')
                ->setParameter('id',$scenario->getId())
                ->getResult();
    }
}
