<?php

namespace Meldon\WotRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterDetailsRepository extends EntityRepository
{
    public function getStartCharacters(Scenario $scenario)
    {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT cd FROM WotRBundle:CharacterDetails cd '
                        . 'WHERE :id MEMBER OF cd.scenario' )
                ->setParameter('id',$scenario->getId())
                ->getResult();
    }
}
