<?php

namespace Meldon\WotRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getCurrentGame($id)
    {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT g, cg, c, f, ad '
                        . 'FROM WotRBundle:Game g '
                        . 'JOIN g.cardGroups cg '
                        . 'LEFT JOIN cg.cards c '
                        . 'JOIN g.fellowship f '
                        . 'LEFT JOIN g.actionDice ad '
                        . 'WHERE g.id = :id '
                        . 'ORDER BY cg.id, c.group, c.position'
                        )
                ->setParameter('id',$id)
                ->getSingleResult();
    }
}
