<?php

namespace Meldon\WotRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SideRepository extends EntityRepository
{
    public function getPlayedSides()
    {
        return $this->getEntityManager()
        ->createQuery(
                'SELECT s FROM WotRBundle:Side s '
                . 'WHERE s.played = true '
                . 'ORDER BY s.id'
                )
        ->getResult();
    }
}
