<?php

namespace Meldon\WotRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnitEntryDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitEntryDetailsRepository extends EntityRepository
{
    public function getStartUnits(Scenario $scenario)
    {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT ued FROM WotRBundle:UnitEntryDetails ued '
                        . 'WHERE :id MEMBER OF ued.scenario' )
                ->setParameter('id',$scenario->getId())
                ->getResult();
    }
}
